services:
  postgres:
    image: postgres:15-alpine
    container_name: gym-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gym-network

  backend:
    image: ghcr.io/lo-ouiiz/cloudnative-backend:${GITHUB_SHA}
    container_name: gym-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3000
      SEED_DB: ${SEED_DB}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - gym-network

  frontend:
    image: ghcr.io/lo-ouiiz/cloudnative-frontend:${GITHUB_SHA}
    container_name: gym-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:80"
    networks:
      - gym-network

volumes:
  pgdata:

networks:
  gym-network:
    external: true
