services:
  backend-blue:
    image: ghcr.io/lo-ouiiz/cloudnative-backend:${COMMIT_SHA}
    container_name: gym-backend-blue
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - gym-network

  frontend-blue:
    image: ghcr.io/lo-ouiiz/cloudnative-frontend:${COMMIT_SHA}
    container_name: gym-frontend-blue
    env_file:
      - .env
    environment:
      VITE_API_URL=http://backend-blue:3000
    networks:
      - gym-network
