map $ACTIVE_COLOR $backend_upstream {
    default backend-blue:3000;
    blue    backend-blue:3000;
    green   backend-green:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://$backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
